#+SETUPFILE: setup.org
#+TITLE: thi.ng/geom

* About the project

** Overview

This project is part of the [[https://github.com/thi-ng/][thi.ng]] collection of Clojure &
Clojurescript libraries. It constitutes the current chapter-in-writing
in a long, ongoing quest to create a comprehensive, cross-platform,
yet easy-to-use API for 2D/3D geometry operations, both common and
more niché. Since geometry is fundamental to so many aspects of design
production, as with its Java based predecessor [[http://toxiclibs.org][toxiclibs]], the
objective is *not* to produce a graphics engine for games or other
specific use cases, but aims to provide geometry related functionality
in a minimal, modular and as re-usable as possible context, thus
making it easy to integrate into a wide number of scenarios: from
architecture, digital fabrication to data visualization, generative
design in general. We attempt to realise this goal by defining almost
all operations as [[file:core.org][polymorphic protocols]] (currently approx. 50 of
them). These are implemented to different extends by the various basic
[[file:types.org][entities/types]] and together form a small domain-specific language
(whilst remaining fully extensible) to easily create, transform &
export geometry. At the core of this DSL is an extensive (and still
growing) set of vector, matrix & quaternion types/operations, which
the rest of the library is built on, currently:

*** Geometric entities

| *2D*           | *3D*                      |
|----------------+---------------------------|
| Vec2           | Vec3                      |
| Matrix32       | Matrix44                  |
|                | Quaternion                |
| Line2          | Line3                     |
| LineStrip2     | LineStrip3 (TBD)          |
| Bezier2        | Bezier3 (TBD)             |
| Circle2        | Sphere                    |
| Ellipse2 (TBD) | Ellipsoid (TBD)           |
| Rect2          | AABB                      |
| Quad2 (TBD)    | Quad3                     |
|                | Tetrahedron               |
| Triangle2      | Triangle3                 |
| Polygon2       | Polygon3 (TBD)            |
| Path2          | Path3 (TBD)               |
|                | Plane                     |
|                | GMesh                     |
| Point quadtree | Point octree              |
|                | SVO (experimental)        |
|                | Isosurface (experimental) |

Once the protocol API is finalized an overview table/graph will show
which types implement which protocols. For now please consult the
source code to see which operations are supported.

*** Geometry operations

In addition to these types, the library also implements these common
operations:

- Automatic spline generation from set of points
- Basic SVG path parsing
- 2D Delaunay triangulation
- 2D convex hull
- Shape extrusion as solid or walled mesh
- Tesselation of simple 2D polygons
- Insetting of simple 2D polygons
- Sutherland-Hodgeman clipping of 2D polygons
- Entity area, circumference & volume calculations
- Entity intersection checks (vs. line, ray, shape)
- Entity to mesh conversion (w/ many options)
- Access entities as graph-like structures (vertices/edges)
- Entity sampling (at fixed resolution or uniform distance)
- Entity subdivision (only lines, rects, quads, tetrahedrons)
- Subdivision meshes (Catmull-Clark, Doo-Sabin, Butterfly)
- 3D Boolean operations on meshes (union, difference, intersection)
- 3D geometry export (PLY, STL, OBJ, OFF formats)

*** API scope

Since this project does not provide any display & rendering
functionality at all, a number of support libraries are being worked
on, incl. WebGL & SVG support via Clojurescript and wrappers &
GUI libraries for JOGL based desktop apps. Together with sister
libraries like [[https://github.com/thi-ng/luxor][luxor]], it's also possible to generate complete 3D
scenes for high quality & high resolution rendering using [[http://luxrender.net][Luxrender]].

Furthermore, providing all functionality under a common API for both
Clojure & Clojurescript, makes it trivial to offload heavy operations
(e.g. large mesh processing) to the server side.

** Library module structure

For the upcoming 0.3.0 release, the project has been restructured into
a number of modules, each addressing a different level of abstraction
and to group namespaces based on functionality. This reduces potential
code bloat for CLJS applications, but should also make it less
daunting for newcomers to navigate the project.

*** [[../geom-core/src/index.org][geom-core]]

This module forms the library's core and is required by all others. It
defines approx. 50 protocols and provides implementations of
fundamental geometry types/functions like 2d/3d vector algebra,
matrices, quaternion (and related convenience constructors &
conversions) and a number of often needed utility functions to deal
with point collections, normals, sampling, triangles etc.

*** [[../geom-types/src/index.org][geom-types]]

This module defines all high-level 2d/3d data types and
implementations of the various core protocols for each. From a user
perspective this module should be considered part of the core, however
it's been split out to dramatically reduce code size for use cases
where only vectors/matrix ops are needed.

*** [[../geom-meshops/src/index.org][geom-meshops]]

This module provides several tools & operations related to working
with meshes, incl. I/O, subdivisions, Delaunay triangulation,
cleaning, CSG/Boolean mesh merge etc.

*** [[../geom-physics/src/index.org][geom-physics]]

This module consists of a simple particle-based physics engine with
Verlet integration and support for behaviors and constaints, both for
individual particles and global. Particles can be connected with
springs of varying stiffness as well as made interdependent using
positive or negative force fields (attractors).

*** [[../geom-svg/src/index.org][geom-svg]]

A module to help with building SVG based visualizations of geom
entities (incl. a customizable 3D mesh renderer w/ shader support).
CLJS support for this module is planned, but currently untested.

*** [[../geom-webgl/src/index.org][geom-webgl]]

This is a pure CLJS module and provides a number of conversion &
rendering functions to simplify the use of types defined in the
=geom-types= module under CLJS with WebGL.

** Status

The project has been in development since late 2011 and is currently
in its 4th iteration/rewrite cycle. It should still be considered
BETA quality. On the other hand, the library has already been used
successfully in several commercial projects over the past 2 years and
can be considered stable for most use cases.

A full test suite, website & tutorials are actively being worked on.

** Example usage

A preliminary list of other projects using this library:

- [[http://holiday2014.movingbrands.com][MB Home installation]]
- [[https://github.com/postspectacular/devart-codefactory/][Google DevArt Co(de)Factory]]
- [[http://github.com/learn-postspectacular/resonate-2014-workshop][Resonate 2014 workshop]]
- [[http://github.com/thi-ng/luxor][Luxor]]
- [[http://github.com/thi-ng/morphogen][Morphogen]]
- [[http://thi.ng/][thi.ng website]]

Several small examples are include in this repo:

- [[geom-types/src/ptf.org][PTF examples]]
- [[geom-svg/src/examples.org][SVG examples]]
- [[geom-webgl/src/demo.org][WebGL demos]]

** Building & testing this project

This project is written in a literate programming format and requires
[[https://www.gnu.org/software/emacs/][Emacs]] & [[http://orgmode.org][Org-mode]] to generate usable source code in [[https://github.com/lynaghk/cljx][CLJX]] form. Assuming
both tools are installed, the easiest way to generate a working
project is via command line (make sure =emacs= is on your path or else
edit its path in =tangle.sh=):

#+BEGIN_SRC bash
  git clone https://github.com/thi-ng/geom.git
  cd geom

  # tangle all modules...
  ./tangle-all.sh

  # ...or just tangle an individual module
  ./tangle.sh geom-core/src/*.org geom-core/test/*.org

  # ...or an individual file
  ./tangle.sh geom-core/src/utils.org
#+END_SRC

Tangling is the process of extracting & combining source blocks from
=.org= files into an actual working project/source tree. This project
currently consists of 30 namespaces and 6800+ lines of code, the
tangling of which takes approx. 20 secs.

Once tangling is complete, you can =cd= into the generated project
directory of a module (=babel= in this case) and then use =lein= as usual.

*** Testing

The =project.clj= files of each module define an alias to trigger a
complete build & tests for both CLJ & CLJS versions.

#+BEGIN_SRC bash
  cd <<module-name>>/babel
  lein cleantest # some tests currently fail due to still missing protocol impls
#+END_SRC

Afterwards, to build the Clojurescript version simply run =lein
cljsbuild test= from the same directory. A small HTML harness for the
resulting JS file is also located in that folder (=babel/index.html=),
allowing for further experimentation in the browser.

*** Working with the REPL

Since the generated =project.clj= files include REPL hooks
for CLJX, editing files in Org-mode, then re-loading & testing changes
is quite trivial. Simply launch a REPL (via lein or Emacs) as usual.
Everytime you've made changes to an =.org= file, re-tangle it from
Emacs or =tangle.sh=, then reload the namespace in the REPL via
=(require 'thi.ng.geom... :reload)= or similar.

** Injected properties                                             :noexport:

#+BEGIN_SRC clojure :exports none :noweb-ref project-name
thi.ng/geom
#+END_SRC

#+BEGIN_SRC clojure :exports none :noweb yes :noweb-ref cljs-artefact-path
target/geom-<<conf-version()>>.js
#+END_SRC

** Leiningen coordinates
#+BEGIN_SRC clojure :noweb yes :noweb-ref lein-coords
  [thi.ng/geom "0.0-710"]
#+END_SRC

** Leiningen project file                                          :noexport:
#+BEGIN_SRC clojure :tangle ../babel/project.clj :noweb yes :mkdirp yes :padline no
  (defproject <<project-name>> "<<conf-version()>>"
    :description  "thi.ng geometry kit - meta project spec including all modules"
    :url          "<<conf-project-url>>"
    :license      {:name "Apache Software License"
                   :url  "http://www.apache.org/licenses/LICENSE-2.0"
                   :distribution :repo}
    :scm          {:name "git"
                   :url  "<<conf-project-url>>"}

    :dependencies [[thi.ng/geom-core "<<conf-version()>>"]
                   [thi.ng/geom-types "<<conf-version()>>"]
                   [thi.ng/geom-meshops "<<conf-version()>>"]
                   [thi.ng/geom-physics "<<conf-version()>>"]
                   [thi.ng/geom-svg "<<conf-version()>>"]
                   [thi.ng/geom-webgl "<<conf-version()>>"]]

    :pom-addition [:developers [:developer
                                [:name "Karsten Schmidt"]
                                [:url "http://postspectacular.com"]
                                [:timezone "0"]]])
#+END_SRC

** Release history

| *Version* | *Released* | *Lein coordinates*        | *Tagged Github URL* |
|-----------+------------+---------------------------+---------------------|
|   0.0-710 | 2014-03-10 | =[thi.ng/geom "0.0-710"]= | [[https://github.com/thi-ng/geom/tree/0.0-710][0.0-710]]             |
|   0.0-709 | 2014-03-10 | =[thi.ng/geom "0.0-709"]= | [[https://github.com/thi-ng/geom/tree/0.0-709][0.0-709]]             |
|     0.2.0 | 2014-03-10 | =[thi.ng/geom "0.2.0"]=   | [[https://github.com/thi-ng/geom/tree/0.2.0][0.2.0]]               |

** Contributors

| *Name*          | *Role*                          | *Website*           |
| [[mailto:k@thi.ng][Karsten Schmidt]] | initiator & principal developer | [[http://postspectacular.com][postspectacular.com]] |
|                 |                                 | [[http://thi.ng][thi.ng]]              |

** License

This project is open source and licensed under the [[http://www.apache.org/licenses/LICENSE-2.0][Apache Software License 2.0]].
